### ISSUE TITLE
Stream Audio

### ISSUE THREAD

**Issue by mis3v** [wayou/audio-visualizer-with-controls#1]
Really cool! I'm wondering why i can't add streaming adress instead of local MP3? 
For example if i change:

`<audio src="assets/sample.mp3" id="audio" controls>audio element not supported</audio>`

to

`<audio src="http://stream.radiocorp.nl/r10_90s_mp3" id="audio" controls>audio element not supported</audio>`

when i disable main.js it's working. So, support for streaming audio would be great :-)

Thanks!

**Comment by wayou** [comment]
> Really cool! I'm wondering why i can't add streaming adress instead of local MP3? 
> For example if i change:
> 
> <audio src="assets/sample.mp3" id="audio" controls>audio element not supported</audio>
> 
> to
> 
> <audio src="http://stream.radiocorp.nl/r10_90s_mp3" id="audio" controls>audio element not supported</audio>
> 
> when i disable main.js it's working. So, support for streaming audio would be great :-)
> 
> Thanks!

there's CORS access restriction from another domain for the audio element. so you have to make audios come from the same server where you code located.

**Comment by mis3v** [comment]
Ok, thanks for your answer!
