### ISSUE TITLE
Uncaught (in promise) DOMException: The element has no supported sources.

### ISSUE THREAD

**Issue by sabreenakp** [wayou/audio-visualizer-with-controls#2]
In the index.html file when src given as an external url then an error arises- which is shown below

```
Uncaught (in promise) DOMException: The element has no supported sources.
```

what is the reason behind this error?

**Comment by wayou** [comment]
external sources are restricted by Cross-origin reason.

**Comment by sabreenakp** [comment]
Hii...Thanks for the reply!

the error arises when i insert audio.crossOrigin="anonymous" to my js file,
i tried removing that and commented the line of code

`var audioSrc = ctx.createMediaElementSource(audio);`

then i can hear the sound but no visualisation, how can i access an mp3 file stored in my s3 bucket?

any help will be appreciated.

**Comment by sabreenakp** [comment]
Hii..Got the solution,Thanks for the reply :-)

**Comment by wayou** [comment]
wut did u do ?

**Comment by sabreenakp** [comment]
The problem lies in the analyzer node. It can only process media that were loaded in compliance with [CORS.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

s3 configuration also changed and set the crossOrigin attribute of the audio element.

**Comment by wayou** [comment]
great! thanks for sharing.
